/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    occasions: Occasion;
    brands: Brand;
    authors: Author;
    retailers: Retailer;
    products: Product;
    'buying-guides': BuyingGuide;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      buyingGuides: 'buying-guides';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    retailers: RetailersSelect<false> | RetailersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'buying-guides': BuyingGuidesSelect<false> | BuyingGuidesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Optional parent category for nested taxonomy (e.g. Kitchen > Blenders).
   */
  parent?: (number | null) | Category;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Seasonal/event taxonomy (Christmas, Halloween, Black Friday...) — independent from product Category so the site can expand beyond seasonal products later without schema changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Month (1-12) shopping interest for this occasion typically starts ramping up.
   */
  startMonth?: number | null;
  /**
   * Month (1-12) the occasion ends (e.g. Christmas: 12).
   */
  endMonth?: number | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Official brand website URL.
   */
  website?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  /**
   * Role/title shown on byline, e.g. "Senior Reviewer".
   */
  title?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * Optional link to the admin user account for this author.
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Affiliate retailers (Amazon, Walmart, Target, Best Buy...). Products link to Retailers with a per-product affiliate URL, so the site is not locked into a single affiliate network.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retailers".
 */
export interface Retailer {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Optional base affiliate URL pattern for this retailer/network (e.g. Amazon Associates tag template), for reference when adding a product affiliate link.
   */
  urlPattern?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  categories?: (number | Category)[] | null;
  /**
   * Which seasonal/event gift guides this product belongs to.
   */
  occasions?: (number | Occasion)[] | null;
  brand?: (number | null) | Brand;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Manufacturer/official product page (non-affiliate).
   */
  officialUrl?: string | null;
  /**
   * Product photo gallery. Drag rows to reorder.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Where this product can be bought, each with its own affiliate URL.
   */
  retailerLinks?:
    | {
        retailer: number | Retailer;
        affiliateUrl: string;
        /**
         * Optional last-known price for display (not live-synced in MVP).
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  pros?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-form key/value spec rows — flexible across any product category.
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  ratings?: {
    /**
     * Overall score out of 10 (supports one decimal, e.g. 8.5).
     */
    overall?: number | null;
    /**
     * Optional per-criterion breakdown (e.g. Performance, Value, Build Quality).
     */
    criteria?:
      | {
          name: string;
          score: number;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional hands-on testing methodology/notes. Leave empty for curated/aggregated reviews.
   */
  testingNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show in featured/homepage placements.
   */
  isFeatured?: boolean | null;
  bestPickLabel?: ('none' | 'best-overall' | 'best-budget' | 'best-upgrade' | 'best-for-beginners') | null;
  seo?: {
    /**
     * Overrides the page <title>. Falls back to the content title if empty.
     */
    metaTitle?: string | null;
    /**
     * Meta description shown in search results (~155 characters).
     */
    metaDescription?: string | null;
    /**
     * Used for both the meta image and as the Open Graph image fallback.
     */
    metaImage?: (number | null) | Media;
    /**
     * Optional Open Graph title override. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Optional Open Graph description override. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  /**
   * Buying guides that reference this product (read-only, managed from Buying Guides).
   */
  buyingGuides?: {
    docs?: (number | BuyingGuide)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buying-guides".
 */
export interface BuyingGuide {
  id: number;
  title: string;
  slug: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  occasion?: (number | null) | Occasion;
  category?: (number | null) | Category;
  author?: (number | null) | Author;
  /**
   * Products featured in this guide, in display order.
   */
  products?: (number | Product)[] | null;
  publishedAt?: string | null;
  seo?: {
    /**
     * Overrides the page <title>. Falls back to the content title if empty.
     */
    metaTitle?: string | null;
    /**
     * Meta description shown in search results (~155 characters).
     */
    metaDescription?: string | null;
    /**
     * Used for both the meta image and as the Open Graph image fallback.
     */
    metaImage?: (number | null) | Media;
    /**
     * Optional Open Graph title override. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Optional Open Graph description override. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'retailers';
        value: number | Retailer;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'buying-guides';
        value: number | BuyingGuide;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startMonth?: T;
  endMonth?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  avatar?: T;
  bio?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retailers_select".
 */
export interface RetailersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  urlPattern?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categories?: T;
  occasions?: T;
  brand?: T;
  description?: T;
  officialUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  retailerLinks?:
    | T
    | {
        retailer?: T;
        affiliateUrl?: T;
        price?: T;
        id?: T;
      };
  pros?:
    | T
    | {
        point?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        point?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ratings?:
    | T
    | {
        overall?: T;
        criteria?:
          | T
          | {
              name?: T;
              score?: T;
              id?: T;
            };
      };
  testingNotes?: T;
  isFeatured?: T;
  bestPickLabel?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
      };
  buyingGuides?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buying-guides_select".
 */
export interface BuyingGuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  occasion?: T;
  category?: T;
  author?: T;
  products?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}